-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 16:52:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce-g11
-- -----------------------------------------------------
-- Diagrams:
-- Users
-- UsersDetails
-- Adress
-- Telephones
-- TypeDocument
-- Products
-- Sales
-- Cobros
-- Tickets
DROP SCHEMA IF EXISTS `ecommerce-g11` ;

-- -----------------------------------------------------
-- Schema ecommerce-g11
--
-- Diagrams:
-- Users
-- UsersDetails
-- Adress
-- Telephones
-- TypeDocument
-- Products
-- Sales
-- Cobros
-- Tickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce-g11` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `ecommerce-g11` ;

-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Address` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference` ENUM('billing', 'shipping') NOT NULL,
  `address_line1` VARCHAR(40) NOT NULL,
  `address_line2` VARCHAR(40) NULL,
  `city` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `idusersdetails` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Cart` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` INT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `cantProducts` INT NULL DEFAULT 0,
  `subtotal` DOUBLE NULL,
  `total` DOUBLE NULL DEFAULT 0,
  `idusersdetails` INT NOT NULL,
  `idcheckout` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Cart_has_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Cart_has_Products` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Cart_has_Products` (
  `Cart_id` INT NOT NULL,
  `Products_id` INT NOT NULL,
  PRIMARY KEY (`Cart_id`, `Products_id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Categorys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Categorys` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Categorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `description` VARCHAR(45) NULL,
  `thumbnail` TINYBLOB NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Confirmation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Confirmation` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Confirmation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tar_credit` INT NOT NULL,
  `banco` VARCHAR(32) NOT NULL,
  `total` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Images` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` MEDIUMBLOB NULL,
  `thumbnail1` TINYBLOB NULL,
  `thumbnail2` TINYBLOB NULL,
  `thumbnail3` TINYBLOB NULL,
  `thumbnail4` TINYBLOB NULL,
  `idproduct` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`OrderSummary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`OrderSummary` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`OrderSummary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `status` ENUM('pending', 'failed', 'paid', 'delivered', 'canceled') NULL DEFAULT 'pending',
  `tax` INT NULL,
  `banco` VARCHAR(32) NULL,
  `idcart` INT NOT NULL,
  `idaddress` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Payment` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tar_credit` INT NOT NULL,
  `banco` VARCHAR(32) NOT NULL,
  `total` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Products` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT(255) NULL,
  `price` DOUBLE NULL DEFAULT 0,
  `cost` DOUBLE NULL DEFAULT 0,
  `stock` INT(10000) NULL DEFAULT 0,
  `colors` TEXT(32) NULL,
  `weight` DECIMAL NULL,
  `freeshiping` TINYINT NULL,
  `averageRating` TINYINT(5) NULL DEFAULT 0,
  `numOfReviews` INT NULL DEFAULT 0,
  `idcategory` INT NOT NULL,
  `idreviews` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Reviews` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` TINYINT(5) NULL,
  `title` TEXT(100) NULL,
  `comment` TEXT(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Telephones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Telephones` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Telephones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Telephone` TINYINT(13) NOT NULL,
  `idusersdetails` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`TypeDocument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`TypeDocument` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`TypeDocument` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nameTD` ENUM('DNI', 'Pasaporte') NULL DEFAULT 'DNI',
  `idusersdetails` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `idusersdetails`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`Users` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'admin',
  `idusersdetails` INT NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `idusersdetails`));


-- -----------------------------------------------------
-- Table `ecommerce-g11`.`UsersDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce-g11`.`UsersDetails` ;

CREATE TABLE IF NOT EXISTS `ecommerce-g11`.`UsersDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(32) NOT NULL,
  `secondname` VARCHAR(32) NULL,
  `lastname` VARCHAR(32) NOT NULL,
  `secondlastname` VARCHAR(32) NULL,
  `document` INT(8) NOT NULL,
  `createAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` TIMESTAMP NULL,
  `Reviews_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Data for table `ecommerce-g11`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `ecommerce-g11`;
INSERT INTO `ecommerce-g11`.`Users` (`id`, `username`, `email`, `password`, `role`, `idusersdetails`, `createAt`, `updateAt`) VALUES (1, 'admin', 'admin@gmail.com', '123456', 'admin', 1, 'TIMESTAMP', 'TIMESTAMP');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
